create or replace TRIGGER "ACSEL"."GB_CONTRATANTE_ADICIONAL" 
BEFORE INSERT OR UPDATE
ON ACSEL.CONTRATANTE_ADICIONAL REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN

   IF INSERTING THEN
      IF :NEW.FEC_CREACION IS NULL THEN 
         :NEW.FEC_CREACION := SYSDATE;
      END IF;
      IF :NEW.USUARIO_CREACION IS NULL THEN
         :NEW.USUARIO_CREACION := CODUSER;
      END IF;
   ELSIF UPDATING THEN
         :NEW.FEC_MODIFICACION := SYSDATE;
         :NEW.USUARIO_MODIFICACION := CODUSER;
   END IF;
END;


