/*
|| Script de COT_PLANTILLA
*/
CREATE TABLE  "COT_PLANTILLA" 
   (    "IDCOTIZAPLANTILLA" NUMBER(15,0) NOT NULL ENABLE, 
    "NBREPLANTILLA" VARCHAR2(200), 
    "CODUSR" VARCHAR2(10), 
    "FECHAREGISTRO" DATE, 
    "FECHAACTUALIZA" DATE, 
    "CODPROD" VARCHAR2(4), 
    "CODPLAN" VARCHAR2(8), 
    "IDCOTIZACION" NUMBER(15,0), 
     CONSTRAINT "COT_PLANTILLA_PK" PRIMARY KEY ("IDCOTIZAPLANTILLA")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COT_PLANTILLA_PK" ON  "COT_PLANTILLA" ("IDCOTIZAPLANTILLA")
/

CREATE SEQUENCE   "COT_PLANTILLA_SEQ"  
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  
    NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COT_PLANTILLA" 
  before insert on "COT_PLANTILLA"               
  for each row  
begin   
  if :NEW."IDCOTIZAPLANTILLA" is null then 
    select "COT_PLANTILLA_SEQ".nextval into :NEW."IDCOTIZAPLANTILLA" from sys.dual; 
  end if; 
end; 

/

ALTER TRIGGER  "BI_COT_PLANTILLA" ENABLE
/
