/*
|| Script de COTIZACION_COBERTURA
*/

CREATE TABLE  "COTIZACION_COBERTURA" 
   ( "IDCOTIZA" NUMBER (15,0), 
    "CODCOBERT" VARCHAR2(8), 
    "INDOBLIGA" VARCHAR2(1), 
    "SUMA_ASEGURADA" NUMBER(12,2), 
    "TASA" NUMBER(14,6), 
    "PRIMA" NUMBER(14,2), 
    "IDCOBERTURA" NUMBER(15,0), 
    "CODRAMOPLAN" VARCHAR2(4), 
     CONSTRAINT "COTIZACION_COBERTURA_PK" PRIMARY KEY ("IDCOBERTURA")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COTIZACION_COBERTURA_PK" ON  "COTIZACION_COBERTURA" ("IDCOBERTURA")
/

ALTER TABLE  "COTIZACION_COBERTURA" ADD CONSTRAINT "COTIZACION_COBERTURA_FK" FOREIGN KEY ("IDCOTIZA")
      REFERENCES  "COTIZACION" ("IDCOTIZA") ENABLE
/

 CREATE SEQUENCE   "COTIZACION_COBERTURA_SEQ"  
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 896 CACHE 5 
    NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COTIZACION_COBERTURA" 
  before insert on "COTIZACION_COBERTURA"               
  for each row  
begin   
  if inserting then
     if :NEW.IdCobertura is null then
        select cotizacion_cobertura_seq.nextval
          into :NEW.IdCobertura
          from dual;
     end if;
  end if;
end;
/

ALTER TRIGGER  "BI_COTIZACION_COBERTURA" ENABLE
/
