/*
|| Script Table COTIZA_CLAUSULA
*/
CREATE TABLE  "COTIZA_CLAUSULA" 
   (    "IDCOTIZA" NUMBER(15,0), 
    "CODCLAUSULA" VARCHAR2(6), 
    "CODRAMO" VARCHAR2(6), 
    "INDCLAUSULAOBLIG" VARCHAR2(1), 
    "FECHA_DESDE" DATE, 
    "FECHA_HASTA" DATE, 
    "NOTAS" VARCHAR2(4000), 
    "IDCOTIZACLAUSULA" NUMBER(15,0), 
     CONSTRAINT "COTIZA_CLAUSULA_CON" PRIMARY KEY ("IDCOTIZACLAUSULA")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COTIZA_CLAUSULA_CON" ON  "COTIZA_CLAUSULA" ("IDCOTIZACLAUSULA")
/

CREATE SEQUENCE   "SEQ_COTIZA_CLAUSULA"  
  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
  INCREMENT BY 1 START WITH 5541 CACHE 5 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "COTIZA_CLAUSULA_T1" 
BEFORE
insert or update or delete on "COTIZA_CLAUSULA"
for each row
begin
if inserting then
   if :NEW.idcotizaclausula is null then
      :NEW.idcotizaclausula := seq_cotiza_clausula.nextval;
   end if;
end if;
end;
/

ALTER TRIGGER  "COTIZA_CLAUSULA_T1" ENABLE
/




