/* Script de Tabla Cotiza_Anexo */

CREATE TABLE  "COTIZA_ANEXO" 
   (    "IDCOTIZA" NUMBER(15,0), 
    "CODANEXO" VARCHAR2(6), 
    "CODRAMO" VARCHAR2(6), 
    "INDANEXOOBLIG" VARCHAR2(1), 
    "FECHA_DESDE" DATE, 
    "FECHA_HASTA" DATE, 
    "IDCOTIZAANEXO" NUMBER(15,0), 
     CONSTRAINT "COTIZA_ANEXO_CON" PRIMARY KEY ("IDCOTIZAANEXO")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

-- Create Index
CREATE UNIQUE INDEX  "COTIZA_ANEXO_CON" ON  "COTIZA_ANEXO" ("IDCOTIZAANEXO")
/

 CREATE SEQUENCE   "SEQ_COTIZA_ANEXO"  
    MINVALUE 1 MAXVALUE 9999999999999999999999999999 
    INCREMENT BY 1 START WITH 36 CACHE 5 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "COTIZA_ANEXO_T1" 
BEFORE
insert or update or delete on "COTIZA_ANEXO"
for each row
begin
 if inserting then
   IF :NEW.IdCotizaAnexo is null then
      :NEW.IdCotizaAnexo := SEQ_COTIZA_ANEXO.NEXTVAL;
   end if;
 end if;
end;

/
ALTER TRIGGER  "COTIZA_ANEXO_T1" ENABLE
/


