/*
|| Script de COT_PLANTILLA_ANEXO
*/
CREATE TABLE  "COT_PLANTILLA_ANEXO" 
   (    "IDCOTPLANTIANEXO" NUMBER(15,0) NOT NULL ENABLE, 
    "IDCOTIZAPLANTILLA" NUMBER(15,0) NOT NULL ENABLE, 
    "CODRAMO" VARCHAR2(4), 
    "CODANEXO" VARCHAR2(4), 
    "INDANEXOOBLIG" VARCHAR2(1), 
     CONSTRAINT "COT_PLANTILLA_ANEXO_PK" PRIMARY KEY ("IDCOTPLANTIANEXO")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COT_PLANTILLA_ANEXO_PK" ON  "COT_PLANTILLA_ANEXO" ("IDCOTPLANTIANEXO")
/

CREATE SEQUENCE "COT_PLANTILLA_ANEXO_SEQ"  
  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
  INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COT_PLANTILLA_ANEXO" 
  before insert on "COT_PLANTILLA_ANEXO"               
  for each row  
begin   
  if :NEW."IDCOTPLANTIANEXO" is null then 
    select "COT_PLANTILLA_ANEXO_SEQ".nextval into :NEW."IDCOTPLANTIANEXO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_COT_PLANTILLA_ANEXO" ENABLE
/
