/*
|| Script de COTIZACION_REQUISITO
*/
CREATE TABLE  "COTIZACION_REQUISITO" 
   (    "CODPROD" VARCHAR2(4) NOT NULL ENABLE, 
    "CODPLAN" VARCHAR2(6) NOT NULL ENABLE, 
    "CODRAMO" VARCHAR2(4) NOT NULL ENABLE, 
    "CODREQ" VARCHAR2(4) NOT NULL ENABLE, 
    "INDOBLIG" VARCHAR2(1), 
    "FECSTS" DATE, 
    "IDREQUISITO" NUMBER(15,0), 
    "STSREQ" VARCHAR2(3), 
    "IDCOTIZACION" NUMBER(15,0), 
    "REQUISITO_PICTURE" BLOB, 
    "MIMETYPE" VARCHAR2(50), 
    "FILENAME" VARCHAR2(200), 
    "CREATED_DATE" DATE, 
     CONSTRAINT "COTIZACION_REQUISITO_PK" PRIMARY KEY ("IDREQUISITO")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COTIZACION_REQUISITO_PK" ON  "COTIZACION_REQUISITO" ("IDREQUISITO")
/

ALTER TABLE  "COTIZACION_REQUISITO" ADD CONSTRAINT "COTIZACION_REQUISITO_CON" FOREIGN KEY ("IDCOTIZACION")
      REFERENCES  "COTIZACION" ("IDCOTIZA") ENABLE
/

CREATE SEQUENCE   "SEQ_COTIZACION_REQUISITO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
  INCREMENT BY 1 START WITH 156 CACHE 5 NOORDER  
  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "COTIZACION_REQUISITO_T1" 
BEFORE
insert or update or delete on "COTIZACION_REQUISITO"
for each row
begin
if inserting then
   if :NEW.IdRequisito is null then
      :NEW.IdRequisito := seq_cotizacion_requisito.nextval;
   end if;
end if;
end;
/

ALTER TRIGGER  "COTIZACION_REQUISITO_T1" ENABLE
/
