/*
|| Script de Tabla COT_PLANTILLA_COBERT
*/
CREATE TABLE  "COT_PLANTILLA_COBERT" 
   (    "IDCOTPLANTILLACOBERT" NUMBER(15,0) NOT NULL ENABLE, 
    "IDCOTIZAPLANTILLA" NUMBER(15,0) NOT NULL ENABLE, 
    "CODRAMO" VARCHAR2(4), 
    "CODCOBERT" VARCHAR2(4), 
    "INDCOBERTOBLIG" VARCHAR2(1), 
    "PRIMA" NUMBER(14,2), 
    "TASA" NUMBER(14,6), 
    "SUMAASEG" NUMBER(14,2), 
    "ORDEN" NUMBER(4,0), 
    "PORCDED" NUMBER(3,2),
    "MTODED" NUMBER(14,2),
    "BASE"   VARCHAR2(2)
   )
/

CREATE UNIQUE INDEX  "COT_PLANTILLA_COBERT_PK" ON  "COT_PLANTILLA_COBERT" ("IDCOTPLANTILLACOBERT")
/

 CREATE SEQUENCE   "COT_PLANTILLA_COBERT_SEQ"  
   MINVALUE 1 MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COT_PLANTILLA_COBERT" 
  before insert on "COT_PLANTILLA_COBERT"               
  for each row  
begin   
  if :NEW."IDCOTPLANTILLACOBERT" is null then 
    select "COT_PLANTILLA_COBERT_SEQ".nextval into :NEW."IDCOTPLANTILLACOBERT" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_COT_PLANTILLA_COBERT" ENABLE
/

