/*
|| Script de Tabla COT_PLANTILLA_CLAUSULA
*/
CREATE TABLE  "COT_PLANTILLA_CLAUSULA" 
   (    "IDCOTPLANTICLAU" NUMBER(15,0) NOT NULL ENABLE, 
    "IDCOTIZAPLANTILLA" NUMBER(15,0), 
    "CODRAMO" VARCHAR2(4), 
    "CODCLAU" VARCHAR2(6), 
    "INDCLAUOBLIG" VARCHAR2(1), 
    "FECHAREGISTRO" DATE, 
    "FECHAACTUALIZA" DATE, 
     CONSTRAINT "COT_PLANTILLA_CLAUSULA_PK" PRIMARY KEY ("IDCOTPLANTICLAU")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE UNIQUE INDEX  "COT_PLANTILLA_CLAUSULA_PK" ON  "COT_PLANTILLA_CLAUSULA" ("IDCOTPLANTICLAU")
/

CREATE SEQUENCE   "COT_PLANTILLA_CLAUSULA_SEQ"  
   MINVALUE 1 MAXVALUE 9999999999999999999999999999 
   INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COT_PLANTILLA_CLAUSULA" 
  before insert on "COT_PLANTILLA_CLAUSULA"               
  for each row  
begin   
  if :NEW."IDCOTPLANTICLAU" is null then 
    select "COT_PLANTILLA_CLAUSULA_SEQ".nextval into :NEW."IDCOTPLANTICLAU" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_COT_PLANTILLA_CLAUSULA" ENABLE
/

