/* Script de Creación de la Tabla de Cotización */
CREATE TABLE  "COTIZACION" 
   (    "IDCOTIZA" NUMBER(15,0), 
    "TIPOID" VARCHAR2(3), 
    "NUMID" NUMBER(15,0), 
    "DVID" VARCHAR2(2), 
    "NOMBRE" VARCHAR2(200), 
    "EMAIL" VARCHAR2(80), 
    "TELEFONO" VARCHAR2(12), 
    "NROMOVIL" VARCHAR2(12), 
    "FECHAREG" DATE, 
    "STSCOTIZA" VARCHAR2(3), 
    "DIASCOTIZA" NUMBER(2,0), 
    "CODPROD" VARCHAR2(4), 
    "CODPLAN" VARCHAR2(8), 
    "CODMONEDA" VARCHAR2(3), 
    "DIRECCION" VARCHAR2(250), 
    "FECDESDE" DATE, 
    "FECHASTA" DATE, 
    "CODINTER" VARCHAR2(8), 
    "APELLIDO" VARCHAR2(200), 
    "CODOFI" VARCHAR2(6), 
    "IDCOTIZAPLANTILLA" NUMBER(15,0), 
    "NOTAS" VARCHAR2(4000), 
    "CODUSR" VARCHAR2(15), 
    "PLANACUERDO" VARCHAR2(4), 
    "PORCINICIAL" NUMBER(8,4), 
    "CUOTAS" NUMBER(2,0), 
    "SERIEID" NUMBER(3,0),
     CONSTRAINT "COTIZACION_PK" PRIMARY KEY ("IDCOTIZA")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

-- Index Primary Key de la Tabla de Cotización
CREATE UNIQUE INDEX  "COTIZACION_PK" ON  "COTIZACION" ("IDCOTIZA")
/

-- Sequence IDCOTIZA de la Tabla Cotización
 CREATE SEQUENCE   "COTIZACION_SEQ"  
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 
 INCREMENT BY 1 START WITH 301 CACHE 20 
 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
