create or replace TRIGGER "ACSEL"."TRIG_ANEXO_CERT_INS_AFTER" 
AFTER INSERT
ON ANEXO_CERT
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW






Begin
  INSERT INTO AU_$ANEXO_CERT(CodUsr,Fecha,IdeANEXO,Operacion)
       --VALUES (User,SYSDATE,:NEW.IdeANEXO,'INSERT');
       VALUES (coduser,SYSDATE,:NEW.IdeANEXO,'INSERT');
End;





